#server:
#  port: 8080
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test0831?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    #url: jdbc:mysql://{공인IP}:{원격서버mysql포트}/test0831?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: zpzzgjdg@$^1
#
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
#      hibernate:
#        format_sql: true
#        highlight_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#        # dialect: org.hibernate.dialect.MySQL8InnoDBDialect
#        boot:
#          allow_jdbc_metadata_access: false
#
#  jwt:
#    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"
#
#  mail:
#    host: smtp.naver.com #smtp ?? ??
#    port: 465 # ?? ???? ??
#    username: swo98@naver.com #??? ???
#    password: zpzzgjdg2461 #??? ????
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          #            required: true
#          auth: true
#          #          connectiontimeout: 5000
#          #          timeout: 5000
#          #          writetimeout: 5000
#          ssl:
#            #trust: smtp.naver.com
#            enable: true #??? ?? -> SSL ??? ?????
#
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      repositories:
#        enabled: false
#
#logging:
#  level:
#    org.hibernate.SQL: debug