version: '3.8'

services:
  backendmodule:
    image: openjdk:17-jdk-slim
    container_name: backendmodule-container
    working_dir: /backendmodule
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "set2"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/moum?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "zpzzgjdg@$$^1"
      SPRING_JWT_SECRET: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"
      SPRING_MAIL_HOST: "smtp.naver.com"
      SPRING_MAIL_PORT: "465"
      SPRING_MAIL_USERNAME: "swo98@naver.com"
      SPRING_MAIL_PASSWORD: "zpzzgjdg2461"
      SPRING_REDIS_HOST: "redis"
      SPRING_NCP_OBJECT_STORAGE_ENDPOINT: "https://kr.object.ncloudstorage.com"
      SPRING_NCP_OBJECT_STORAGE_REGION: "kr-standard"
      SPRING_NCP_OBJECT_STORAGE_ACCESS_KEY: "ncp_iam_BPAMKR2MhBwOgB3j1oI5"
      SPRING_NCP_OBJECT_STORAGE_SECRET_KEY: "ncp_iam_BPKMKRCDtYOBhPsxfs0g1Rtl1OV6bBsPtG"
      SPRING_NCP_OBJECT_STORAGE_BUCKET: "moumstorage"
      SPRING_NAVER_API_KEY_ID: "3kitedtcgg"
      SPRING_NAVER_API_KEY: "FPL9KPlKtuGgTcr4mFV2HLVIpVDT1mTjyQgAWMrt"
      SPRING_NAVER_MAPS_API_URL: "https://naveropenapi.apigw.ntruss.com"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: zpzzgjdg@$$^1
      MYSQL_DATABASE: moum
    ports:
      - "3301:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6371:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
