##version: '3'
##
##services:
##  app:
##    build:
##      context: .             # 현재 디렉터리에서 빌드
##      dockerfile: Dockerfile   # Dockerfile 파일명
##    restart: always
##    ports:
##      - "8080:8080"
##    environment:
##      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test0831?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: zpzzgjdg@$^1
##      SPRING_JPA_HIBERNATE_DDL_AUTO: create
##    depends_on:
##      - db                    # db 서비스가 먼저 시작되도록 의존성 설정
##    networks:
##      - network
##
##  db:
##    image: mysql:8.0
##    environment:
##      MYSQL_ROOT_PASSWORD: zpzzgjdg@$^1
##      MYSQL_DATABASE: test0831
##    ports:
##      - "3306:3306"
##    networks:
##      - network
##
##  redis:
##    image: redis:latest
##    ports:
##      - "6379:6379"
##    networks:
##      - network
##
##networks:
##  network:
#version: '3'
#
#services:
#  app:
#    build:
#      context: .             # 현재 디렉터리에서 빌드
#      dockerfile: Dockerfile   # Dockerfile 파일명
#    #restart: always
#    ports:
#      - 8080:8080
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#    depends_on:
#      - db                    # db 서비스가 먼저 시작되도록 의존성 설정
#    networks:
#      - network
#
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: zpzzgjdg@$^1
#      MYSQL_DATABASE: test0831
#    ports:
#      - 3306:3306
#    networks:
#      - network
#
#  redis:
#    image: redis:latest
#    ports:
#      - 6379:6379
#    networks:
#      - network
#
#networks:
#  network:
