version: '3.8'

services:
  backendmodule:
    image: openjdk:17-jdk-slim
    container_name: backendmodule-container-green
    working_dir: /backendmodule
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "zpzzgjdg@$$^1"
      SPRING_JWT_SECRET: "${SPRING_JWT_SECRET}"
      SPRING_MAIL_HOST: "${SPRING_MAIL_HOST}"
      SPRING_MAIL_PORT: "${SPRING_MAIL_PORT}"
      SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD}"
      SPRING_REDIS_HOST: "${SPRING_REDIS_HOST}"
      SPRING_NCP_OBJECT_STORAGE_ENDPOINT: "${SPRING_NCP_OBJECT_STORAGE_ENDPOINT}"
      SPRING_NCP_OBJECT_STORAGE_REGION: "${SPRING_NCP_OBJECT_STORAGE_REGION}"
      SPRING_NCP_OBJECT_STORAGE_ACCESS_KEY: "${SPRING_NCP_OBJECT_STORAGE_ACCESS_KEY}"
      SPRING_NCP_OBJECT_STORAGE_SECRET_KEY: "${SPRING_NCP_OBJECT_STORAGE_SECRET_KEY}"
      SPRING_NCP_OBJECT_STORAGE_BUCKET: "${SPRING_NCP_OBJECT_STORAGE_BUCKET}"
      SPRING_NAVER_API_KEY_ID: "${SPRING_NAVER_API_KEY_ID}"
      SPRING_NAVER_API_KEY: "${SPRING_NAVER_API_KEY}"
      SPRING_NAVER_MAPS_API_URL: "${SPRING_NAVER_MAPS_API_URL}"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container-green
    environment:
      MYSQL_ROOT_PASSWORD: "zpzzgjdg@$^^1"
      MYSQL_DATABASE: moum
    ports:
      - "3301:3306"
    volumes:
      - mysql_data_blue:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container-green
    ports:
      - "6371:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data_blue: