management:
  endpoints:
    web:
      enabled: true
      exposure:
        include: health,info

server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  address: 0.0.0.0

spring:
  application:
    name: chat-app-module
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  r2dbc:
    url: r2dbc:mysql://mysql-backend-container:3306/moum?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    host: mysql-backend-container
    port: 3306
    database: moum
    username: root
    password: zpzzgjdg@$^1
    driver: mysql
    pool:
      enabled: true
  sql:
    init:
      platform: mysql

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"
  data:
    mongodb:
      host: chatdb.f9mra.mongodb.net
      port: 27017
      database: chatdb
      username: cjaehyuk4zed
      password: ChatDB2024
      authentication-database: admin
      options: ?retryWrites=true&w=majority&appName=ChatDB
      connection-timeout: 3000
      max-wait-time: 10000
      pool:
#        By default, min-size = 0 and max-size = 100
        min-size: 10
#        max-size: 100
        max-idle-time: 60000 # 60 seconds
#        max-life-time: 60000
        initial-size: 10
        validate-query: { "ping": 1 }

    redis:
      host: redis-chat-container
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: 3000
          shutdown-timeout: 100

# Debug log configs, change as needed when logging or debugging
logging:
  level:
    org.springframework.web: TRACE
#    org.mongodb.driver: DEBUG
